[workspace]
members = ["crates/tokf-cli", "crates/tokf-common", "crates/tokf-server"]
resolver = "2"

[workspace.package]
edition = "2024"
license = "MIT"
repository = "https://github.com/mpecan/tokf"
homepage = "https://tokf.net"
