[package]
name = "tokf-cli"
version = "0.2.5"
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Config-driven CLI tool that compresses command output before it reaches an LLM context"
keywords = ["llm", "cli", "tokens", "ai", "context-window"]
categories = ["command-line-utilities", "development-tools"]

[lib]
name = "tokf"

[[bin]]
name = "tokf"
path = "src/main.rs"

[dependencies]
tokf-common = { path = "../tokf-common", version = "0.2.5" }
clap = { version = "4", features = ["derive"] }
toml = "1.0"
serde = { version = "1", features = ["derive"] }
regex = "1"
anyhow = "1"
dirs = "6"
serde_json = "1"
include_dir = { version = "0.7", features = ["glob"] }
rusqlite = { version = "0.38", features = ["bundled"] }
rkyv = { version = "0.8", features = ["bytecheck", "unaligned"] }
mlua = { version = "0.11.6", features = ["luau", "vendored", "error-send"] }

[dev-dependencies]
cargo-husky = { version = "1", default-features = false, features = ["user-hooks"] }
tempfile = "3"
serial_test = "3"

[lints.clippy]
unwrap_used = "deny"
expect_used = "deny"
panic = "deny"
todo = "deny"
pedantic = { level = "warn", priority = -1 }
nursery = { level = "warn", priority = -1 }
module_name_repetitions = "allow"
must_use_candidate = "allow"
