name = "running containers show compact format"
fixture = "success.txt"
exit_code = 0

[[expect]]
contains = "NAMES"

[[expect]]
contains = "webserver"

[[expect]]
not_contains = "CONTAINER ID"

[[expect]]
not_contains = "COMMAND"
