command = "cargo build"
skip = [
  "^   Compiling ",
  "^    Checking ",
  "^    Updating ",
  "^   Downloaded ",
  "^  Downloading ",
  "^     Locking ",
]

[on_success]
output = "ok âœ“"

[on_failure]
tail = 30
